### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by sroze**
Because it's so painful to do that every time.

### CODE REVIEW

**Comment by sroze** [comment]
Right now, it uses only a Redux middleware to catch the errors. What it means is that it does not work with asynchronous processing and sagas. To do so, we'd need to have a list of action names or a convention to detect actions related to an error, and "report the error". The "problem" means that developers would have to `try ... catch` in the sagas... any idea to catch errors in sagas automatically? 🤔

**Comment by thib92** [comment]
So if I understand well, the idea here is to avoid `try ... catch` in the sagas, and only do it in the Redux middleware. How about a more abstracted error handler, and you could provide some kind of service that users can use in their API-request service, and they just need to call a method.
Like `errorHandler.catchError(e)`, or something like that (just like what we do with the logger and Sentry at Birdie). I don't know if this defeats the purpose of this package..

**Comment by hungrydavid** [comment]
Considering a lot of creating sagas is boilerplate anyway. Its almost always call endpoint, put success action with response or put fail action. So potentially something like a saga factory would be useful. That way you could have a catch block setup to report errors by default.

The problem I've seen a few times before, is when sagas have a catch setup to dispatch an error action, they then swallow the error and it fails silently (aside from the action trigger).

**Comment by hungrydavid** [comment]
Essentially a way to create a saga along these lines
```
  createSaga(API_ENDPOINT, TRIGGER_ACTION, SUCCESS_ACTION, FAIL_ACTION)
```

**Comment by thib92** [comment]
I feel this would be very limiting, as I guess a lot of sagas would need a bit of logic after receiving the response.
But why not something like :
```javascript
createSaga(sagaLogic, TRIGGER_ACTION, SUCCESS_ACTION, FAIL_ACTION)
```

And then the `sagaLogic` function could throw at any time to trigger the `FAIL_ACTION`

Maybe even passing event creators, that would be able to have a payload attached to it ?

**Comment by hungrydavid** [comment]
I tend to think that if you have much more in a saga than call and response, you probably have too much responsibility in there. They really shouldn't be much more than an async event handler. 

But you are right that it won't always be the case. Perhaps the simplest defaults, with easy override capabilities would capture the best of both approaches?

**Comment by sroze** [comment]
> createSaga(API_ENDPOINT, TRIGGER_ACTION, ...)

@hungrydavid what would be `API_ENDPOINT` in a real exemple? Another action type?

I also believe this defeats the purpose of the saga which is, i believe so far, more about having a real process manager logic than just on `put`ing. I quite like @thib92’s idea that we could tweak like this:
```javascript
const mySaga = handleErrors(function*() {
  yield ...;
  // ...
});
```

That would do a super basic error handling as in dispatching an action we know about a display the error message within the « ErrorWrapper ». Additionally, we can provide the following “extension” points:
```javascript
// Custom error message
const mySaga = handleErrors(function*() {
  // ...
}, {
  message: e => “You can’t do that”,
});

// Custom error actions
const mySaga = handleErrors(function*() {
  // ...
}, {
  actions: { failure: actionCreator },
});
```

WDYT?

**Comment by thib92** [comment]
I am not sure this implementation would provide a lot of value. It does not reduce the syntax a lot compared to some manual `try / catch` inside the saga, and makes it a little harder to understand @sroze

**Comment by hungrydavid** [comment]
@sroze With api endpoint, I was thinking essentially a call handler function - essentially an api client. The bit you might now write as 
`const response = yield call(getCoachesFromApi)`
Like

```
getUsers() {
  fetch ...
}
```

In terms of the actual implementation of the error handling, I think I prefer the createSaga approach more. I tend to agree with @thib92 here that this last example isn't saving a whole lot of effort. Also I think if we can provide a mechanism that doesn't use the generator syntax if possible, it would be better. Its not the easiest thing for everyone to understand if they haven't come across it before.

What kind of logic are you talking about having in a saga? I think maybe we are misunderstanding each other here.

**Comment by Tketa** [comment]
Hey guys, jumping on here because I've been thinking about refactoring the error handling in the Birdie app.

Really cool that you are mutualising the work! It actually makes sense, every app needs that.

To handle the side effects, the solutions you've raised here seem quite overcomplicated to me. Why don't you use the `onError` callback you can pass to the `createSagaMiddleware` function which will  process all the un-`catch`ed errors and dispatch a  `reportError` action?

**Comment by hungrydavid** [comment]
This is a good point. The only issue is that if you say want to trigger a fail action if an api call fails (likely), you would need to catch the error in the calling saga to dispatch it.

This would then prevent the error from bubbling up to the onError handler. You can work round that by re-throwing or filtering http responses (ie 401 is acceptable).

But there are probably fairly high chances that someone will forget to do this.

I'd quite like the end implementation to reduce the amount of code the developer needs to write.
There is a good chance that this is a slightly separate issue though.

**Comment by Tketa** [comment]
> But there are probably fairly high chances that someone will forget to do this.

If you catch an error it's your responsability to take care of it.. It could actually be because the guy does not want the error to go to Sentry ^^'

**Comment by hungrydavid** [comment]
> Not sure I understand this point? Here it will prevent the dev from having to try {} catch {} everywhere, so less code.
If you're talking about the boilerplate that you have to write when creating sagas, I agree but indeed it should probably be discussed separately :)

You do understand the point - your second point covers it. I was going off topic 😄

**Comment by thib92** [comment]
@hungrydavid I don't agree on your point of removing generator functions : the entire point of Redux Saga is to use them.
If a user wants to avoid them, he can just use redux-thunk which works great as well.
I caught up on Birdie's code base 3 weeks ago with Sagas everywhere, without having used generators functions before, and I understood how it works quite fast.
I think they are hard to understand when used in "vanilla", which is not the case with redux-saga.

Regarding the error handling, I think it would be hard to propose a high value to users without giving a very opinionated tool. I don't know if the goal of Galette is to be opinionated or not, but if it's not, it will be difficult to provide anything really useful IMO.

**Comment by sroze** [comment]
> Why don't you use the `onError` callback you can pass to the `createSagaMiddleware` function which will process all the un-catched errors and dispatch a reportError action?

Very good point; that's probably enough :).

**Pull request merged**
